---
# Handlers pour le r√¥le wazuh-agent

- name: restart wazuh-agent
  systemd:
    name: wazuh-agent
    state: restarted
    daemon_reload: yes

- name: stop wazuh-agent
  systemd:
    name: wazuh-agent
    state: stopped

- name: start wazuh-agent
  systemd:
    name: wazuh-agent
    state: started
    enabled: yes
