---
# Handlers pour le r√¥le wazuh-server

- name: restart wazuh-manager
  systemd:
    name: wazuh-manager
    state: restarted
    daemon_reload: yes

- name: restart wazuh-indexer
  systemd:
    name: wazuh-indexer
    state: restarted
    daemon_reload: yes

- name: restart wazuh-dashboard
  systemd:
    name: wazuh-dashboard
    state: restarted
    daemon_reload: yes

- name: reload systemd
  systemd:
    daemon_reload: yes
